### ISSUE TITLE
Is there any way to contact you? I have a question

### ISSUE THREAD

**Issue by GameboyVlol** [martymcvry/smartschool-api#1]

**Comment by martymcvry** [comment]
You can ask your question here or contact me through my work e-mail: [martijn.verstraelen@gomalle.net](mailto:martijn.verstraelen@gomalle.net). Bear in mind that I've started this thing, but never finished implementing all functions that are available in the API. (It's still a work in progress...)

**Comment by GameboyVlol** [comment]
do you have discord?

**Comment by martymcvry** [comment]
Yeah, sure. Username MartyMcVry#5949

Op za 24 dec. 2022 om 14:21 schreef GameboyVlol ***@***.***>:
